version: "3"

vars:
  SDK: /opt/vertica/sdk
  VSQL: "/opt/vertica/bin/vsql -U dbadmin -w${APP_DB_PASSWORD}"
  SRC: src
  DDL: ddl

tasks:
  default:
    cmds:
      - task --list-all

  install:
    cmds:
      - "{{.VSQL}} -f {{.DDL}}/install.sql"

  uninstall:
    cmds:
      - "{{.VSQL}} -f {{.DDL}}/uninstall.sql"

  test:
    cmds:
      - "{{.VSQL}} -f {{.DDL}}test.sql"
